### PR TITLE
Feature/up to date charts

### PR DESCRIPTION
**Pull request by 0sewa0**

### CODE REVIEW

**Comment by DTMad** [comment]
Please either add or remove the platform check for all files.

**Comment by DTMad** [comment]
Do we need to have the `default` folder within the chart folder?

**Review by DTMad — CHANGES_REQUESTED** [review]
Please test to deploy the charts again - I experienced troubles when deploying dynatrace-operator chart with `platform: kubernetes`

**Comment by 0sewa0** [comment]
> Do we need to have the `default` folder within the chart folder?
@DTMad 
it can be named anything, but it needs to be a folder unfortunately, GKE demands it

**Review by DTMad — APPROVED** [review]

**Pull request merged**
