### PR TITLE
Use native yaml values for objects and lists

### PR DESCRIPTION
**Pull request by Synehan**
Hello,

A small PR in order to have a better visibility in the values.yaml file about default values (for exemple : tolerations and args) and for a better comprehensions of what type of values are expected, migrate from `""`string empty values to specific empty values ({} or []) depending on the type.

### CODE REVIEW

**Comment by merlindorin** [comment]
bump :)

**Comment by DTMad** [comment]
We will internally check and test this change and then merge it

**Comment by merlindorin** [comment]
@DTMad do we have an ETA or we should work on our fork? this issue is stale for a long time now :'(

**Comment by chrismuellner** [comment]
This is possible in the latest version of the dynatrace-operator helm chart.

**Pull request closed without merging**
