### PR TITLE
admissionregistration.k8s.io/v1beta1 deprecated

### PR DESCRIPTION
**Pull request by li-adrienloiseau**
Replacing admissionregistration.k8s.io/v1beta1 by admissionregistration.k8s.io/v1

### CODE REVIEW

**Comment by DTMad** [comment]
Thanks for the PR!
This is definitely a thing we should change.
We normally do such changes directly on the operator repo (https://github.com/Dynatrace/dynatrace-oneagent-operator) and port all the changes there over here whenever we create a new version.

I will create myself an internal ticket for this and fix it on the operator directly and merge it for the next version over here, ok?

**Comment by lrgar** [comment]
Is there a tool that is complaining about this deprecated type?

It's supposed to be removed with 1.19 but it should work regardless on existing Kubernetes versions - supposedly as in, I haven't seen the removal mentioned on the K8s 1.19 changelogs so far.

As for why it matters, we still support K8s/OCP versions that don't yet support the v1 type (it needs K8s 1.16+)

**Comment by li-adrienloiseau** [comment]
> Thanks for the PR!
> This is definitely a thing we should change.
> We normally do such changes directly on the operator repo (https://github.com/Dynatrace/dynatrace-oneagent-operator) and port all the changes there over here whenever we create a new version.
> 
> I will create myself an internal ticket for this and fix it on the operator directly and merge it for the next version over here, ok?

Hello @DTMad ,
thank you for your feedback !
Do you have visibility on the availability of this version?

**Comment by li-adrienloiseau** [comment]
> s there a tool that is complaining about this deprecated type?



> Is there a tool that is complaining about this deprecated type?
> 
> It's supposed to be removed with 1.19 but it should work regardless on existing Kubernetes versions - supposedly as in, I haven't seen the removal mentioned on the K8s 1.19 changelogs so far.
> 
> As for why it matters, we still support K8s/OCP versions that don't yet support the v1 type (it needs K8s 1.16+)

On our platform eks v1.16 this version is deprecated not removed (v1.19):
`[verify_templates]

NAME                         KIND                           VERSION                                REPLACEMENT                       DEPRECATED IN   REMOVED IN  
chaoskube                    Deployment                     apps/v1beta1                           apps/v1                           v1.9.0          v1.16.0     
oneagentapms.dynatrace.com   CustomResourceDefinition       apiextensions.k8s.io/v1beta1           apiextensions.k8s.io/v1           v1.16.0         v1.19.0     
oneagents.dynatrace.com      CustomResourceDefinition       apiextensions.k8s.io/v1beta1           apiextensions.k8s.io/v1           v1.16.0         v1.19.0     `

**Comment by lrgar** [comment]
Thanks. For reference, the removal of CustomResourceDefinition and MutatingWebhookConfiguration's v1beta1 types has been postponed until Kubernetes 1.22.

These deprecated types should still work on any Kubernetes version currently supported by Dynatrace and continue to do so until K8s 1.22 has been released.

As we, Dynatrace, still support Kubernetes 1.15 who doesn't access to the new types, my opinion would be to leave the deprecated versions be for the time being, otherwise we'd need to provide custom manifests and a Helm Chart for K8s 1.15 users.

**Pull request closed without merging**
